### PR TITLE
Ensure CKAN compatibility

### LINKED ISSUE #20: Crashes during fetch stage when attempting to harvest
Crashes during fetch stage due to not calling `check_access`
On attempting to harvest the following endpoint:
https://api.figshare.com/v2/oai

With the following settings:
```json
{ 
  "credentials": null,
  "metadata_prefix": "oai_dc"
}
```

### PR DESCRIPTION
**Pull request by metaodi**
Fixes #20

### CODE REVIEW

**Comment by metaodi** [comment]
This is an attempt to make this extension compatible with newer versions of CKAN.

The extension still has a lot of old code that needs refactoring, but this should do the trick for now.

**Comment by camfindlay** [comment]
❤️  thanks for this. We'll look to do some peer review and testing :)

**Comment by anotheredward** [comment]
Hi @metaodi !

This PR fixes the crashes we were seeing, thanks again for your excellent work :).

**Comment by metaodi** [comment]
@anotheredward thanks for testing!

**Comment by anotheredward** [comment]
@metaodi Just a head's up, changing the name from `OAI-PMH` to `oai-pmh` is a breaking change, all existing harvests that have been setup in the interface will need to be edited, their harvester type re-selected, and saved again (or a database script run if there are a lot) :). Otherwise they'll crash with the error: `System error - No harvester could be found for source type OAI-PMH`

**Pull request merged**
